### ISSUE TITLE
Documentation example error, attribute field code

### ISSUE THREAD

**Issue by cmarfil** [rinvex/sparse#9]
Hello,

In the documentation there is the following example to create an attribute.

```php
Attribute::create(['code' => 'size', 'name' => ['en' => 'Product Size'], 'type' => '\Rinvex\Sparse\Models\Data\Varchar', 'entities' => ['App\Models\Company', 'App\Models\Product']]);
```

But, the "code" field is not used in the Attribute model:

Attribute.php:
```php
    protected $fillable = [
        'name',
        'slug',
        'description',
        'order',
        'group',
        'type',
        'entities',
        'collection',
        'default',
    ];
```
So, if code field is not used, how can I save the value of a simple attribute?
I think there is a need to clarify this point in the documentation.

This would not work:

```php
Attribute::create(['code' => 'size', 'name' => ['en' => 'Product Size'], 'type' => '\Rinvex\Sparse\Models\Data\Varchar', 'entities' => ['App\Models\Company', 'App\Models\Product']]);

$company = App\Models\Company::find(1);
$company->size = '123';
$company->save();
```

Thanks,
Regards.

**Comment by Omranic** [comment]
Will followup about this issue on the newly rebranded package here https://github.com/rinvex/attributable/issues/2

P.S. The old package is now obsolete and no longer maintained, but will keep working for you normally. It's still available on Github & Packagist so don't worry (it's still recommended to switch to the new one). Sorry for any inconvenience!
